package docker

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/wchomik/picolo/config"
)

// Client wraps docker CLI operations
type Client struct {
	config *config.Config
}

// New creates a new docker client
func New(cfg *config.Config) *Client {
	return &Client{config: cfg}
}

// runDocker executes a docker command and returns combined output
func (c *Client) runDocker(args ...string) (string, error) {
	cmd := exec.Command("docker", args...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		output := stderr.String()
		if output == "" {
			output = stdout.String()
		}
		return "", fmt.Errorf("docker %s failed: %w\nOutput: %s", strings.Join(args, " "), err, output)
	}
	return stdout.String(), nil
}

// runDockerCompose executes a docker compose command in the given directory
func (c *Client) runDockerCompose(composeFile string, args ...string) (string, error) {
	fullArgs := append([]string{"compose", "-f", composeFile}, args...)
	return c.runDocker(fullArgs...)
}

// PullImage pulls a docker image
func (c *Client) PullImage(image string) error {
	fmt.Printf("  Pulling image: %s\n", image)
	if _, err := c.runDocker("pull", image); err != nil {
		return fmt.Errorf("failed to pull %s: %w", image, err)
	}
	return nil
}

// ComposeFile returns the path to the generated docker-compose file
func (c *Client) ComposeFile() string {
	return filepath.Join(c.config.HomeDir, "docker-compose.yaml")
}

// GenerateComposeFile creates the docker-compose.yaml
func (c *Client) GenerateComposeFile() error {
	composeContent := c.buildComposeContent()
	composePath := c.ComposeFile()

	if err := os.MkdirAll(c.config.HomeDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	return os.WriteFile(composePath, []byte(composeContent), 0644)
}

func (c *Client) buildComposeContent() string {
	var sb strings.Builder

	sb.WriteString("# Generated by picolo - do not edit manually\n")
	sb.WriteString("services:\n\n")

	if c.config.IsLlamaEnabled() {
		sb.WriteString(c.buildLlamaService())
		sb.WriteString("\n")
	}

	sb.WriteString(c.buildPIAgentService())

	return sb.String()
}

func (c *Client) buildLlamaService() string {
	var sb strings.Builder

	sb.WriteString("  llama-cpp:\n")
	sb.WriteString(fmt.Sprintf("    image: %s\n", c.config.LlamaImage()))
	sb.WriteString("    container_name: llama-cpp\n")
	sb.WriteString("    restart: unless-stopped\n")
	sb.WriteString("    ports:\n")
	sb.WriteString(fmt.Sprintf("      - \"%d:8080\"\n", c.config.LlamaPort))
	sb.WriteString("    volumes:\n")
	sb.WriteString("      - ~/.models:/models\n")

	// GPU configuration
	switch c.config.Env {
	case config.LlamaCUDA:
		sb.WriteString("    deploy:\n")
		sb.WriteString("      resources:\n")
		sb.WriteString("        reservations:\n")
		sb.WriteString("          devices:\n")
		sb.WriteString("            - driver: nvidia\n")
		sb.WriteString("              count: all\n")
		sb.WriteString("              capabilities: [gpu]\n")
	case config.LlamaROCM:
		sb.WriteString("    devices:\n")
		sb.WriteString("      - /dev/kfd\n")
		sb.WriteString("      - /dev/dri\n")
		sb.WriteString("    group_add:\n")
		sb.WriteString("      - video\n")
		sb.WriteString("    environment:\n")
		sb.WriteString("      - HSA_OVERRIDE_GFX_VERSION=11.0.0\n")
	case config.LlamaMetal:
		// Metal is macOS-only, no special GPU config needed for docker
		// (runs on host directly typically)
	case config.LlamaVulkan:
		sb.WriteString("    volumes:\n")
		sb.WriteString("      - ~/.models:/models\n")
		// Vulkan uses host GPU directly, no special config
	}

	sb.WriteString("    command:\n")
	sb.WriteString("      - \"--models-preset\"\n")
	sb.WriteString("      - \"/models/config.ini\"\n")
	sb.WriteString("      - \"--models-max\"\n")
	sb.WriteString("      - \"1\"\n")
	sb.WriteString("      - \"--host\"\n")
	sb.WriteString("      - \"0.0.0.0\"\n")

	return sb.String()
}

func (c *Client) buildPIAgentService() string {
	var sb strings.Builder

	sb.WriteString("  pi-agent:\n")
	sb.WriteString(fmt.Sprintf("    image: %s\n", c.config.PIAgentImage))
	sb.WriteString("    container_name: pi-agent\n")

	if c.config.IsLlamaEnabled() {
		sb.WriteString("    depends_on:\n")
		sb.WriteString("      - llama-cpp\n")
	}

	sb.WriteString("    ports:\n")
	sb.WriteString(fmt.Sprintf("      - \"%d:7681\"\n", c.config.TtydPort))
	sb.WriteString("    volumes:\n")

	piConfigDir := filepath.Join(c.config.HomeDir, "pi")
	sb.WriteString(fmt.Sprintf("      - %s:/root/.pi\n", piConfigDir))
	sb.WriteString("      - ${HOST_PATH:-.}:/app\n")
	sb.WriteString("    environment:\n")

	if c.config.IsLlamaEnabled() {
		sb.WriteString("      - PI_LLM_ENDPOINT=http://llama-cpp:8080/v1\n")
	} else {
		sb.WriteString("      - PI_LLM_ENDPOINT=http://host.docker.internal:8080/v1\n")
	}

	sb.WriteString(fmt.Sprintf("      - PI_EXTENSIONS=%s\n", c.config.ExtensionsString()))
	sb.WriteString("    stdin_open: true\n")
	sb.WriteString("    tty: true\n")

	return sb.String()
}

// PullAll pulls all required images
func (c *Client) PullAll() error {
	if c.config.IsLlamaEnabled() {
		if err := c.PullImage(c.config.LlamaImage()); err != nil {
			return err
		}
	}
	return c.PullImage(c.config.PIAgentImage)
}

// PullAllCompose pulls all images via docker compose
func (c *Client) PullAllCompose() error {
	fmt.Println("  Pulling latest images via docker compose...")
	_, err := c.runDockerCompose(c.ComposeFile(), "pull")
	return err
}

// StartLlama starts the llama-cpp server
func (c *Client) StartLlama() error {
	if !c.config.IsLlamaEnabled() {
		fmt.Println("  Llama.cpp server is disabled (skip_llama=true)")
		return nil
	}
	fmt.Println("  Starting llama-cpp server...")
	_, err := c.runDockerCompose(c.ComposeFile(), "up", "-d", "llama-cpp")
	if err != nil {
		return fmt.Errorf("failed to start llama-cpp: %w", err)
	}
	fmt.Println("  ✓ llama-cpp server started")
	return nil
}

// StopAll stops all services
func (c *Client) StopAll() error {
	_, err := c.runDockerCompose(c.ComposeFile(), "down")
	return err
}

// RunChat starts pi-agent interactively (runs `pi` directly, bypassing ttyd entrypoint)
func (c *Client) RunChat(workDir string) error {
	os.Setenv("HOST_PATH", workDir)

	// Build extension flags: -e ext1 -e ext2 ...
	var cmdArgs []string
	cmdArgs = append(cmdArgs, "compose", "-f", c.ComposeFile(), "run", "--rm", "pi-agent")
	// Override entrypoint: run `pi` directly instead of ttyd
	cmdArgs = append(cmdArgs, "pi")
	for _, ext := range c.config.Extensions {
		cmdArgs = append(cmdArgs, "-e", ext)
	}

	cmd := exec.Command("docker", cmdArgs...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

// RunServe starts pi-agent in ttyd mode
func (c *Client) RunServe(workDir string) error {
	os.Setenv("HOST_PATH", workDir)

	_, err := c.runDockerCompose(c.ComposeFile(), "up", "-d", "pi-agent")
	if err != nil {
		return fmt.Errorf("failed to start pi-agent: %w", err)
	}

	fmt.Printf("  ✓ pi-agent started in ttyd mode\n")
	fmt.Printf("  Open http://localhost:%d in your browser\n", c.config.TtydPort)
	return nil
}

// RestartContainer restarts a specific container via docker compose
func (c *Client) RestartContainer(name string) error {
	_, err := c.runDockerCompose(c.ComposeFile(), "up", "-d", name)
	return err
}

// IsContainerRunning checks if a container is running
func (c *Client) IsContainerRunning(name string) (bool, error) {
	output, err := c.runDocker("ps", "--filter", fmt.Sprintf("name=%s", name), "--filter", "status=running", "--format", "{{.Names}}")
	if err != nil {
		return false, err
	}
	return strings.TrimSpace(output) == name, nil
}

// CheckDocker verifies docker is available
func CheckDocker() error {
	if _, err := exec.LookPath("docker"); err != nil {
		return fmt.Errorf("docker is not installed or not in PATH")
	}

	cmd := exec.Command("docker", "info")
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker is not running: %w", err)
	}

	return nil
}
